# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  username: <%= ENV['IDCFUSER'] %>
  password: <%= ENV["IDCFPWD"] %>
  webhookurl: <%= ENV['URL'] %>
  token: <%= ENV['TOKEN'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
